### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by omry** [bohoro/MoveFastAI#1]
Thanks for trying out Hydra! :)

Here is some config feedback:

```yaml
dataset:
 name: fcluster
 path: /private/home/bohoro/MoveFastAI/Tabular/data/
```

can be written as this to be portable:
```yaml
dataset:
 name: fcluster
 path: ${env:HOME}/MoveFastAI/Tabular/data/
```
This would actually eliminate the need for another dataset config in this simple example).

https://github.com/bohoro/MoveFastAI/blob/302300638617fa6098156b04bf86006b994199f0/Tabular/tab_trainer.py#L19-L20

in your master config.yaml, you can have:

```yaml

defaults:
 - dataset: mac_os

dataset:
 name: ???
 path: ???
 training_data: ${dataset.path}/train.csv.gz
 testing_data: ${dataset.path}/test.csv.gz
```
